In [2]:
help(eval)


Help on built-in function eval in module builtins:

eval(source, globals=None, locals=None, /)
    Evaluate the given source in the context of globals and locals.

    The source may be a string representing a Python expression
    or a code object as returned by compile().
    The globals must be a dictionary and locals can be any mapping,
    defaulting to the current globals and locals.
    If only globals is given, locals defaults to it.



In [8]:
s = eval(input("enter your salary: "))
t = eval(input("enter thte tax percentage: "))
tax = (s/100)*t
print("your salary after tax is :",s - tax)

enter your salary:  10000
enter thte tax percentage:  5


your salary after tax is : 9500.0


In [10]:
n = int(input("enter a number between 1 and 100 :"))
sn = n**2
print("the square of ",n ,"is ",sn)

enter a number between 1 and 100 : 5


the square of  5 is  25


In [14]:
import random
r = random.randint(1,100)
print("the square of ",r ,"is :",r**2)

the square of  82 is : 6724


In [16]:
d = int(input("enter a distance in km :"))
r = int(input("enter rate per km : "))
print("total charge will be :",d*r)

enter a distance in km : 10
enter rate per km :  5


total charge will be : 50


In [18]:
d = int(input("enter the bill in dollars: "))
print("dollar is not accpeted ")
r = int(input("enter dollar value in ruppes :"))
print("your bill will be ",d*r, "ruppes only")

enter the bill in dollars:  50


dollar is not accpeted 


enter dollar value in ruppes : 80


your bill will be  4000 ruppes only


In [22]:
import time
d = int(input("enter the bill in dollars: "))
time.sleep(3)  #delays the next line of code  by 3 sec
print("dollar is not accpeted ")
r = int(input("enter dollar value in ruppes :"))
time.sleep(3)
print("your bill will be ",d*r, "ruppes only")

enter the bill in dollars:  40


dollar is not accpeted 


enter dollar value in ruppes : 80


your bill will be  3200 ruppes only


In [16]:
d = int (input("enter distance in kilometers : "))
if d >10:
    print("charge is 100")
elif(7 <= d <=10):
    print("charge is 70 ")
elif (4 <= d < 7):
    print("charge is 40 ")
else :
    print("charge is 30 ")

enter distance in kilometers :  2


charge is 30 


In [10]:
#factorial of a number 
f=1
x= int(input("enter the number:"))
for i in range(1,x+1):
    f= f*i

print(f)

enter the number: 5


120


In [22]:
#factorial of a number 
f=1
x= int(input("enter the number:"))
if x<0:
    print("can't find the factorial")
elif x==0:
    print("the factorial is 1")
else:
    for i in range(1,x+1):
        f= f*i
    print("the factorial of {} is {}".format(x,f))

enter the number: 5


the factorial of 5 is 120


In [28]:
#fibbonacci series
x=int(input('enter the number:'))
first=0
second=1
print(first,second,end=' ')
for i in range(2,x+1):
    num=first+second
    print(num,end=' ')
    first=second
    second=num


enter the number: 5


0 1 1 2 3 5 

In [32]:
# swapping of numbers
a=input('enter a number a:')
b=input('enter a number b:')
c=a
a=b
b=c
print('now a is {}\n now b is {}'.format(a,b))

enter a number a: 4
enter a number b: 5


now a is 5
 now b is4


In [44]:
# spliting of a string
string=input("enter a string: ")
li1=string.split()
print(li1[::-1])

enter a string:  he has a bee


['bee', 'a', 'has', 'he']


In [50]:
str1=input("enter a string")
for i in str1:
    print(i)


enter a string heello


h
e
e
l
l
o


In [72]:
# prime number or not
x=int(input("enter a number : "))
count=0
if x<=0:
    print("number not valid")
elif x==1:
    print("1 is prime number")
else:
    for i in range(2,x):
        if x%i==0:
            count+=1
            break
    if count==1:
        print('not prime')
    else:
        print('prime')
        

enter a number :  6


not prime


In [96]:
# armstrong number 
num= int(input("enter the number : "))
sum=0
n=num
power= len(str(num))
while num>0:
    digit=num%10
    sum += digit**power
    num= num//10

if sum==n:
    print('it is an amstrong number')

else:
    print('the number is not amstrong number')

enter the number :  153


it is an amstrong number


In [100]:
# second largest number in a list
lis1=[2,89,56,34,78]
lis1.sort()
print(lis1[-2])

78


In [108]:
# palindrom of a number
num= int(input("enter a number : "))
sum=0
n=num
while num>0:
    digit=num%10
    sum= (sum*10)+digit
    num = num//10
if n==sum:
    print("it is a palindrom")

else:
    print("it is not a palindrom")

enter a number :  2332


it is a palindrom


In [117]:
#star patterns 
rows=int(input("enter the number of rows :"))
for i in range(rows+1):
    for j in range(i):
        print(i,end=' ')
    print('')

enter the number of rows : 5



1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [127]:
#square patterns 
rows=int(input("enter the number of rows :"))
for i in range(1,rows+1):
    for j in range(rows):
        print(i,end=' ')
    print('')

enter the number of rows : 5


1 1 1 1 1 
2 2 2 2 2 
3 3 3 3 3 
4 4 4 4 4 
5 5 5 5 5 


In [131]:
# pascal triangle
rows=5
for i in range(rows):
    print(''*(rows-1),end=' ')
    print(i)

 0
 1
 2
 3
 4


In [135]:
# matrix multiplication
import numpy as np
a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.array([[1,2,3],[1,2,3],[1,2,3]])
c = np.dot(a,b)
print(c)

[[ 3  6  9]
 [ 6 12 18]
 [ 9 18 27]]
